extends:minimal.conf
zsh
neovim
ripgrep
python

pre:termux-change-repo
pre:pkg upgrade -y

post:echo '------------------'
post:chsh -s zsh && echo 'restart for zsh'
post:echo 'termux settings:         ~/.termux/termux.properties'
post:echo 'recommended apps:        Termux:Styling, Termux:Api'
post:echo 'after shell restart run: p10k configure'
