music_directory     "~/Documents/music"
playlist_directory  "~/Documents/music/playlists"

auto_update     "yes"
bind_to_address "127.0.0.1"
restore_paused  "yes"

audio_output {
  type "pulse"
  name "pulse"
  #type "alsa"
  #name "ALSA"
}
