#!/bin/bash

SESSION_NAME=software
PROJECT_PATH=$SOFTWARE

tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]; then
  tmux new-session -s $SESSION_NAME -n editor -d
  tmux send-keys -t $SESSION_NAME "cd $PROJECT_PATH" C-m
  tmux send-keys -t $SESSION_NAME "$EDITOR ." C-m

  tmux split-window -h -p 30 -t $SESSION_NAME
  tmux send-keys -t $SESSION_NAME:1.2 "cd $PROJECT_PATH" C-m

  tmux select-pane -t $SESSION_NAME:1.1
fi

tmux attach -t $SESSION_NAME
