# -*- conf -*-

include=~/.config/foot/theme.ini

font=0xProto Nerd Font:style=Regular:size=9
font-bold=0xProto Nerd Font:style=Bold:size=9
font-italic=0xProto Nerd Font:style=Italic:size=9

[scrollback]
lines=10000

[key-bindings]
clipboard-paste=Control+v XF86Paste

[text-bindings]
\x17 = Control+BackSpace

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape

[mouse]
hide-when-typing=yes

[colors]
alpha=0.9
